### ISSUE TITLE
is there any way to make this compatible with BOP?

### ISSUE THREAD

**Issue by Wolfram96** [superfluke/somelikeitdry#2]
Hi this mod is awesome and i realise this isn't a classical issue but rather a request.

I just love how this mod allows me to combine the custom terrain from vanilla aka remove waterlakes, lavalakes, caves and ravines as well as making the biomeborders more smooth due to this mod., It all makes the landscape more pleasing even if mining becomes a chore. Now all i need is this with the diversity of BOP and it would be perfect(or close, BOPs terrain gen sucks) but alas i cant make it work. Probably BOPs world gen is at fault and not yours, but maybe you could look into it, i'd appreciate it, thx.

Wolfram

**Comment by superfluke** [comment]
I've looked before and it's no small feat making the two mods work together (since they both override the same bit of code). However, I'm fairly sure that BoP has a 'land mass %' option that lets you reduce the amount water from within that mod. Otherwise, try checking out Traverse for some extra biomes which should play nice with SLID.
